spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ahsankabir007/config-server
          repos:
            - patterns: multi-repo-demo-*
              uri: https://github.com/ahsankabir007/config-server

server:
  port: 8086



